ALGORITHM = "tfidf" # options: bayesian, tfidf, ctfidf
ANNOTATE_FIRST_OCCURRENCE_ONLY = False
REMOVE_PREDEFINED_STOPWORDS_DURING_GENERATING_TOP_TOKENS = False
TOKENIZATION_RANGE = [1, 1]
SMOOTH_IDF = False # Only for ALGORITHM = "tfidf"
CALCULATE_FOR_EACH_CLASS_SEPARATELY = True # Only for ALGORITHM = "tfidf"
USE_SUBLINEAR_TF_SCALING = True # Only for ALGORITHM = "tfidf"